services:
  - type: web
    name: caneryilmazsports-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: starter
    region: frankfurt
    branch: main
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
    healthCheckPath: /health