services:
  - type: web
    name: cys-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: CHROME_PATH
        value: /usr/bin/chromium
    healthCheckPath: /health
